-- Add Form 40 specific fields to licence_applications
ALTER TABLE licence_applications
    ADD COLUMN case_type VARCHAR(50),
    ADD COLUMN previous_rc_number VARCHAR(100),
    ADD COLUMN drug_name VARCHAR(255),
    ADD COLUMN generic_name VARCHAR(255),
    ADD COLUMN brand_name VARCHAR(255),
    ADD COLUMN drug_class VARCHAR(100),
    ADD COLUMN pharmacopoeia VARCHAR(50),
    ADD COLUMN dosage_form VARCHAR(100),
    ADD COLUMN strength_composition VARCHAR(255),
    ADD COLUMN route_of_administration VARCHAR(100),
    ADD COLUMN therapeutic_category VARCHAR(100),
    ADD COLUMN proposed_indications TEXT,
    ADD COLUMN pack_size VARCHAR(100),
    ADD COLUMN storage_conditions VARCHAR(255),
    ADD COLUMN shelf_life VARCHAR(50),
    ADD COLUMN manufacturer_name VARCHAR(255),
    ADD COLUMN manufacturing_site_id VARCHAR(100),
    ADD COLUMN manufacturing_site_address TEXT,
    ADD COLUMN country_of_origin VARCHAR(100),
    ADD COLUMN manufacturing_license_number VARCHAR(100),
    ADD COLUMN approval_status_origin_country VARCHAR(100),
    ADD COLUMN foreign_regulatory_approvals TEXT,
    ADD COLUMN application_fee DECIMAL(12,2),
    ADD COLUMN payment_mode VARCHAR(50),
    ADD COLUMN payment_reference VARCHAR(100),
    ADD COLUMN payment_date TIMESTAMPTZ,
    ADD COLUMN arn_number VARCHAR(50) UNIQUE,
    ADD COLUMN applicant_dsc_token VARCHAR(255),
    ADD COLUMN digital_signed BOOLEAN DEFAULT FALSE,
    ADD COLUMN signatory_name VARCHAR(255),
    ADD COLUMN dsc_signed_at TIMESTAMPTZ,
    ADD COLUMN assigned_officer_name VARCHAR(255),
    ADD COLUMN assignment_date TIMESTAMPTZ,
    ADD COLUMN scrutiny_status VARCHAR(50),
    ADD COLUMN deficiency_remarks TEXT,
    ADD COLUMN applicant_response_deadline DATE;

-- Create inspections table
CREATE TABLE inspections (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    application_id UUID NOT NULL REFERENCES licence_applications(id),
    inspector_id UUID,
    inspection_type VARCHAR(50),
    inspection_date DATE,
    team_members TEXT,
    gps_latitude DOUBLE PRECISION,
    gps_longitude DOUBLE PRECISION,
    checklist_json TEXT,
    critical_observations TEXT,
    observation_severity VARCHAR(20),
    inspection_report_url VARCHAR(255),
    photo_urls_json TEXT,
    decision_status VARCHAR(50),
    approval_conditions TEXT,
    rejection_reason_code VARCHAR(50),
    rejection_narrative TEXT,
    rc_license_number VARCHAR(50) UNIQUE,
    license_validity_years INTEGER,
    license_issue_date DATE,
    license_expiry_date DATE,
    officer_signed BOOLEAN DEFAULT FALSE,
    signing_officer_name VARCHAR(255),
    signed_at TIMESTAMPTZ,
    status VARCHAR(50) DEFAULT 'SCHEDULED',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);
